// Auto-generated
let project = new Project('starter');

project.addSources('Sources');
project.addLibrary("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/armory");
project.addLibrary("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/iron");
project.addLibrary("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/lib/haxebullet");
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/lib/haxebullet/ammo/ammo.wasm.js", { notinlist: true });
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/lib/haxebullet/ammo/ammo.wasm.wasm", { notinlist: true });
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('arm.node.NodeTree');
project.addParameter("--macro keep('arm.node.NodeTree')");
project.addParameter('arm.CubeSpawner');
project.addParameter("--macro keep('arm.CubeSpawner')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('arm.node.TankTree');
project.addParameter("--macro keep('arm.node.TankTree')");
project.addParameter('arm.node.Player1Controls');
project.addParameter("--macro keep('arm.node.Player1Controls')");
project.addShaders("build_starter/compiled/Shaders/*.glsl", { noembed: false});
project.addShaders("build_starter/compiled/Hlsl/*.glsl", { noprocessing: true, noembed: false });
project.addAssets("build_starter/compiled/Assets/**", { notinlist: true });
project.addAssets("build_starter/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/armory/Assets/hosek/hosek_radiance.hdr", { notinlist: true });
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/armory/Assets/hosek/hosek_radiance_0.hdr", { notinlist: true });
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/armory/Assets/hosek/hosek_radiance_1.hdr", { notinlist: true });
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/armory/Assets/hosek/hosek_radiance_2.hdr", { notinlist: true });
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/armory/Assets/hosek/hosek_radiance_3.hdr", { notinlist: true });
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/armory/Assets/hosek/hosek_radiance_4.hdr", { notinlist: true });
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/armory/Assets/hosek/hosek_radiance_5.hdr", { notinlist: true });
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/armory/Assets/hosek/hosek_radiance_6.hdr", { notinlist: true });
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/armory/Assets/hosek/hosek_radiance_7.hdr", { notinlist: true });
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("D:/VAULT_ARMORY3D/ArmorySDK1912/ArmorySDK/armory/Assets/smaa_search.png", { notinlist: true });
project.addAssets("grid_rough.png", { notinlist: true });
project.addDefine('arm_hosek');
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_cascade=4096');
project.addDefine('rp_shadowmap_cube=2048');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=TAA');
project.addDefine('arm_veloc');
project.addDefine('arm_taa');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_ssgi=RTAO');
project.addDefine('rp_bloom');
project.addDefine('rp_ssr');
project.addDefine('rp_gbuffer2');
project.addDefine('arm_audio');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_noembed');
project.addDefine('arm_soundcompress');
project.addDefine('arm_skin');
project.addDefine('arm_particles');


resolve(project);
